re_accronyms = {
        r'!':'.',
        r'ang\.(?=[\s,\.])': 'angående',
        r'a\/s': 'a_s',
        r'(\satt(\.)?)(?=[\s,\.])': ' til',
        r'dbh(\.)?(?=[\s,\.])': 'de bedste hilsener',
        r'\b(bh\.|bh)(?=[\s,\.])': 'bedste hilsener',
        r'(ca\.|ca)(?=[\s,\.])': 'cirka',
        r'\b(dp)': 'dagpenge',
        r'd\.d\.': 'dags dato',
        r'\sd\.': ' den',
        r'dkk': 'kr',
        r'dvs': 'det vil sige',
        r'\b(evt(\.))': 'eventuelt',
        r'((eu\/)eøs-land|eøs-land|eøs\sland|(eu\/)eøs|eøs)': 'eøs_land',
        r'i\.f\.m\.': 'i forbindelse med',
        r'ift': 'i forhold til',
        # r'i\sforbindelse\smed':'i forbindelse med',
        r'jf\.(?=[\s,\.])': 'jævnfør',
        r'(km\.|km)(?=[\s,\.])': 'kilometer',
        r'kroner': 'kr',
        # r'læs\snærmere\si':'',
        r'mdr\.s': 'måneder',
        r'mdr': 'måneder',
        r'mdr\.': 'måneder',
        r'medl\.': 'medlem',
        r'(m\.m\.|mm\.)(?=[\s,\.])': 'med mere',
        r'(o\.s\.v\.|osv\.)(?=[\s,\.])': 'og så videre',
        r'mvh(\.)?(?=[\s,\.])': 'med venlig hilsen',
        r'pft\.': '',
        r'ph\.d\.|ph\.d|phd': 'philosophiaedoctor',
        r'på\sforhånd\stak': '',
        r'pr\.': 'pr',
        r'(pt\s|pt\.)(?=[\s,\.])': 'for tiden',
        r'sp\.':'spørgsmål',
        r'tak\sfor\sdet':'',
        r'(?<=([0-9])\s)t(?=[\s,\.])' : 'timer',
        r'(?<=([0-9]))t(?=[\s,\.])': ' timer',
        r'\b(tlf)': 'telefon',
        r'vedr\.': 'vedrørende',
        r'vedr(?=[\s,\.])': 'vedrørende',
        }

re_system = { # remove these
        r'inden for 5 minutter kan du logge på aka':'',
        r'du skal logge på selvbetjeningen':'',
        r'((du skal logge på selvbetjeningen for at læse)(\sbrevet,)?( som ligger i)?(\sdin)?(\sindbakke)?)':'',
        r'\b(?:du har fået)+.*.(?:a-kasse:)':'', # du har fået brev fra akademikernes a-kasse:
}

re_keyconcepts ={
        r'(0\s(kroner|kr)(\.)?)(?=[\s,\.])':'nul_kr',
        r'\b(0)\s': 'nul ',
        r'\b(?:14\sdage)': '14_dage',
        r'\b(?:30\stimer)': '30_timer',
        r'\b(?:30\sår)': '30_år',
        r'\b(?:5\sår)': '5_år',
        r'\b(?:8\suger)': '8_uger',
        r'\b(?:aka\.dk)': 'aka_dk',
        r'\b(aka(\s|-)joblog(gen)?)|\b(jobloggen)': 'aka_jobloggen',
        r'\b(?:(barselsorlov|barsel))': 'barsel',
        r'\b(?:blevet\sudmeldt\spr)': 'blevet_udmeldt_pr',
        r'\b(?:blevet\sopsagt)': 'blevet_opsagt',
        r'\b(?:cvr\s(nummer|nr))': 'cvr_nr',
        r'\b(?:cpr\s(nummer|nr))': 'cpr_nr',
        r'\b(?:det\skan\sdu)': 'det_kan_du',
        r'\b(?:du\ser\shermed)': 'du_er_hermed',
        r'\b(?:du\shar\sfået)': 'du_har_fået',
        r'\b(?:du\skan\sfå)(?=[\s,\.])': 'du_kan_få',
        r'\b(?:du\skan\slæse)': 'du_kan_læse',
        r'\b(?:du\sfinde(r))': 'du_finder',
        r'\b(?:du\shar)': 'du_har',
        r'\b(?:du\shøre(r))': 'du_høre',
        r'\b(?:du\sskal)': 'du_skal',
        r'\b(?:foretage\smig)' : 'foretage_mig',
        r'\b(?:g(\s|-)dage(n)?)(?=[\s,\.])': 'g_dage',
        # r'\b(?:gået\spå\s(barselsorlov|barsel))': 'gået_på_barsel',
        # r'\b(?:gået\spå\s(deltidsefterløn|deltid))': 'gået_på_deltid',
        # r'\b(?:gået\spå\sefterløn)': 'gået_på_efterløn',
        # r'\b(?:gået\spå\sfædreorlov)': 'gået_på_fædreorlov',
        # r'\b(?:gået\spå\sorlov)': 'gået_på_orlov',
        # r'\b(?:gået\spå\s(folkepension|pension))': 'gået_på_pension',
        r'\b(?:gået\spå)': 'gået_på',
        r'\b(?:har\sdu\sspørgsmål)': 'har_du_spørgsmål', # check
        r'\b(?:har\ssendt)': 'har_sendt',
        r'\b(?:i\shar\sfået\s)': 'i_har_fået',
        r'\b(?:ikke\sfået)': 'ikke_fået',
        r'\b(?:ikke\sdeltage(r)?)(?=[\s,\.])': 'ikke_deltage',
        r'\b(?:jeg\shar\s(få|modtag)et)': 'jeg_har_modtaget', # Concatenated with 'fået'
        r'\b(?:jeg\sforetage(r))' : 'jeg_foretage',
        r'\b((efter\saftale)|(som\saftalt))': 'som_aftalt',
        r'\b(?:er\sdu\svelkommen\stil\sat)': 'er_du_velkommen_til_at',
        r'\b(forstår\sikke)': 'forstår_ikke',
        r'\b(?:gratis\sstudiemedlemskab)': 'gratis_studiemedlemskab', # check
        r'\b(?:gå\spå)': 'gå_på',
        r'\b(hver\småned(er)?)(?=[\s,\.])': 'hver_måned',
        r'\b(hver\sdag\s)': 'hver_dag ',
        r'\b(hver\suge)': 'hver_uge',
        r'\b(har\si\smulighed)': 'har_i_mulighed',
        r'\b(intern\sserverfejl(, det er vores skyld)?)': 'intern_serverfejl',
        r'\b(jeg\sforetage(r)?)(?=[\s,\.])': 'jeg_foretage',
        r'\b(jeg\sophøre(r)?)(?=[\s,\.])': 'jeg_ophøre',
        r'\b(jobnet(\.dk)?)(?=[\s,\.])': 'jobnet_dk',
        r'\b(kan\si\stjekke)': 'kan_i_tjekke', # Indicates a request for information
        r'\b(konto(\s)?nr)': 'konto_nr',
        r'(?<=\s)\w[a-zæøå]*kontrakt*(er|en)?(?!\s{2,})': 'kontrakt', # 20181020 - takes all forms of *kontrakt
        r'\b(?:laveste\sdagpengesats)': 'laveste_dagpengesats', # check
        r'\b((ledig(e)?\stid(er)?))': 'ledige_tider',
        r'\b(?:log(ge)?\spå)': 'log_på',
        r'\b(?:log(ge)?\sind)': 'logge_ind',
        r'\b(?:melde\sdig\sind)': 'melde_dig_ind',
        r'\b(?:melde\sdig\sud)': 'melde_dig_ud',
        r'\b(?:melde\ssig)': 'melde_sig',
        r'\b(?:mindre\send)': 'mindre_end',
        r'\b(min\sret)': 'min_ret',
        r'\b(min\sopsigelse)': 'min_opsigelse',
        r'\b(mit(\s|-)aka)': 'mit_aka',
        r'\b(?:modtage\sen\sbekræftelse)': 'modtage_en_bekræftelse', # check this
        r'\b(nedsat\stid(er)?)(?=[\s,\.])': 'nedsat_tid', # check this
        r'\b(ny(e)?\sadresse)': 'ny_adresse',
        r'\b(?:offentlig\sforsørgelse)': 'offentlig_forsørgelse',
        r'\b(?:opfylder\skravene)': 'opfylder_kravene',
        r'\b(?:(folkepension|pension))': 'pension',
        r'(?<=\s)\w[a-zæøå]*praktik*(?!\s{2,})': 'praktik', # 20181020 - takes all forms of *praktik
        r'\b(ring(e)?\stil\sos)' : 'ringe_til_os',
        r'\b(?:sket\sen\sfejl)': 'sket_en_fejl', #(\b((der|det)\s(var|er|må)?\w*\s))?\b
        r'\b(?:skift\smedlemskab)': 'skift_medlemskab',
        r'\b(?:skulle\sder\svære)': 'skulle_der_være', # check this
        r'\b(?:spørgsmål\stil)': 'spørgsmål_til', # check this
        r'\b(?:studerende\sover\s30\sår)' : 'studerende over_30_år',
        r'\b(?:su\sberettiget)': 'su_berettiget',
        r'\b(supplerende dagpenge)':'supplerende_dagpenge',
        r'(?<=\s)\w[a-zæøå]*tillæg*(get|gene)?(?!\s{2,})': 'tillæg', # 20181020 - takes all forms of *tillæg
        r'\b(til\sgode(?=[\s,\.]))': 'til_gode',
        r'\b(tro\slove(\s|\sog\s)erklæring(s))': 'tro_love_erklæring',
        r'udbetaling\sdanmark':'udbetaling_danmark',
        r'\b(udbetalesspecifikation(en)?)(?=[\s,\.])':'udbetales specifikation',
        }

re_lemma = {
        r'\b(afhold(es|te|er|e|t)?)(?=[\s,\.])': 'afholde',
        r'\b(afgørelse(n)?)(?=[\s,\.])': 'afgørelse',
        r'\b(afslut(ning(en)?|tet|ter|te)?)(?=[\s,\.])': 'afslutte',
        r'\b(ansøg(ning(er|en)?|te|e)?)(?=[\s,\.])': 'ansøgning',
        r'\b(aps|anpartsselskab)': 'aps',
        r'\b(arbejds(plads|giver))': 'arbejdsplads',
        r'\b(arbejdsmarket)': 'arbejdsmarked',
        r'\b(arbejd(estime|estimer|stime|stimer))': 'timer',
        r'\b(arbejd(ede|et|er|e|t)?)(?=[\s,\.])': 'arbejde',
        r'(behandle(ren|t|r)?)(?=[\s,\.])': 'behandle', # Corrects all forms of words ending in variants of 'behandle'
        r'\b(beklag(else|et|es|er|e)?)(?=[\s,\.])': 'beklage',
        r'\b(bekræft(else|et|es|er|e)?)(?=[\s,\.])': 'bekræfte',
        r'\b(beløb(et|e)?)(?=[\s,\.])': 'beløbe',
        r'\b(beregn(ing|et|e)?)(?=[\s,\.])': 'beregne',
        r'\b(besked(erne|er|en)?)(?=[\s,\.])': 'besked',
        r'(betal(ing(en)?|ende|een|es|te|er|t|e)?)(?=[\s,\.])': 'betale', # Corrects all forms of words ending in variants of 'betale'
        r'\b(betyd(ning|et|er|e)?)(?=[\s,\.])': 'betyde',
        r'\b(book(er|et|es|e))': 'book',
        r'\b(bo(ede|r)?)(?=[\s,\.])': 'bopæl',
        r'\b(brug(er|es|te|t|e)?)(?=[\s,\.])': 'bruge',
        r'\b(blankette(n|r)?)(?=[\s,\.])': 'blanket',
        r'\b(brev(et|e)?)(?=[\s,\.])': 'brev',
        r'\b(dag(en|es|s))(?=[\s,\.])': 'dage',
        r'\b(dagpenge(ne|s)?)(?=[\s,\.])': 'dagpenge',
        r'\b(deltage(lse|r)?)(?=[\s,\.])': 'deltage',
        r'\b(dokumentation(en)?)(?=[\s,\.])': 'dokumentation',
        r'(erklæring(en|er)?)(?=[\s,\.])': 'erklæring',
        r'\b(efterløn(nen)?)(?=[\s,\.])': 'efterløn',
        r'\b(fejl(en|i))': 'fejl',
        r'\b(ferie\sdagpenge(ne)?)(?=[\s,\.])':'feriedagpenge',
        r'\b(ferie\spenge(ne)?)(?=[\s,\.])':'feriepenge',
        r'\b(feriedag(e)?)(?=[\s,\.])': 'feriedage',
        r'\b(ferieår(et)?)(?=[\s,\.])': 'ferieår',
        r'\b(ferie(n))': 'ferie',
        r'\b(fil(type(r)?|erne|er|en)?)(?=[\s,\.])': 'fil',
        r'\b(find(er|e)?)(?=[\s,\.])': 'finde',
        r'\b(firma(et))': 'firma',
        r'\b(flyt(ning|tede|tet|ter|tes|te)?)(?=[\s,\.])': 'flytte',
        r'\b(frigørlses(sattest|attest|atest)?)(?=[\s,\.])': 'frigørlsesattest',
        r'\b(frivillig(e|t))': 'frivillig',
        r'\b(forlæng(else|et|er|e)?)(?=[\s,\.])': 'forlænge',
        r'\b(forstå(ende|r)?)(?=[\s,\.])': 'forstår',
        r'\b(fortsæt(ter|te)?)(?=[\s,\.])': 'fortsætte',
        r'\b(fremsend(te|er|e)?)(?=[\s,\.])': 'fremsende',
        r'\b(fyld(ning(erne|ne|er)?|er|et|e|t)?)(?=[\s,\.])': 'fylde',
        r'\b(følg(er|e)?)(?=[\s,\.])': 'følge',
        r'\b(glem(mer|te|me|t)?)(?=[\s,\.])': 'glemme',
        r'\b(godkend(er|te|t|e)?)(?=[\s,\.])': 'godkende',
        r'\b(grund(et|e)?)(?=[\s,\.])': 'grunde',
        r'\b(hjemmeside(r|n)?)(?=[\s,\.])': 'hjemmeside',
        r'\b(hold(et|er|e|t)?)(?=[\s,\.])': 'holde',
        r'\b(hurtig(ere|est|st|e)?)(?=[\s,\.])': 'hurtig',
        r'\b(høre(r|t))': 'høre',
        r'\b(indberette(r|t))': 'indberette',
        r'\b(indsend(er|e|t)?)(?=[\s,\.])': 'indsende',
        r'\b(informer(et|e)?)(?=[\s,\.])': 'informere',
        r'\b(information(erne|er)?)(?=[\s,\.])': 'information',
        r'\b(info)(?=[\s,\.])': 'information',
        r'\b(jobcent(eret|ret|er)?)(?=[\s,\.])': 'jobcenter',
        r'\b(joblog(gen))': 'joblog',
        r'\b(jobopslag(ene|et)?)(?=[\s,\.])': 'jobopslag',
        r'\b(jobsøg(ende|ningen|ning)?)(?=[\s,\.])': 'jobsøgende',
        r'\b(job(bet|s)?)(?=[\s,\.])': 'job',
        r'\b(job(\s)?net(\.dk|dk|e)?)(?=[\s,\.])': 'jobnet_dk',
        r'\b(kandidat(en))': 'kandidat',
        r'\b(karakter(e))(?=[\s,\.])': 'karakter',
        r'\b(karriere(r|n)?)(?=[\s,\.])': 'karriere',
        r'\b(karantæne(r|n)?)(?=[\s,\.])': 'karantæne',
        r'\b(kig(ge|ger|get)?)(?=[\s,\.])': 'kigge',
        r'\b(kode(ord)?)(?=[\s,\.])': 'kode',
        r'\b(kollega(erne|er))': 'kollega',
        r'\b(kommunen|kommune)': 'kommunen',
        r'\b(konti(n)?gent(et)?)(?=[\s,\.])': 'kontigent',
        r'\b(kontakt(er|e)?)(?=[\s,\.])': 'kontakte',
        r'\b(kontrakt(en))(?=[\s,\.])': 'kontrakt',
        r'\b(korrekt(e))': 'korrekt',
        r'\b(kort(ene|et)?)(?=[\s,\.])': 'kort',
        r'\b(kurs(et|us|er))(?=[\s,\.])': 'kursus',
        r'\b(ledig(es|e)?)(?=[\s,\.])': 'ledig',
        r'\b(lukke(t))': 'lukke',
        r'\b(logge(t))': 'logge',
        r'\b(lyd(er|e)?)(?=[\s,\.])': 'lyde',
        r'\b(læs(er|e)?)(?=[\s,\.])': 'læse',
        r'\b(løn(net|nen|en|et))': 'løn',
        r'\b(lønsed(deler|lerne|del|ler|))(?=[\s,\.])': 'lønseddel',
        r'\b(løntime(en|er)?)(?=[\s,\.])': 'time',
        r'\b(mangle(nde|s|t|r)?)(?=[\s,\.])': 'mangle',
        r'\b(medarbejder(eren|ere|er|e))': 'medarbejder',
        r'(meld(else|ing|es|te|er|e|t)?)(?=[\s,\.])': 'melde',  # Corrects all forms of words ending in variants of 'melde'
        r'\b(meddel(elsen|elser|else|er|t|e))': 'meddele',
        r'\b(medlemsskab(et)?)(?=[\s,\.])': 'medlemskab',
        r'\b(medlem(met|mer|et)?)(?=[\s,\.])': 'medlem',
        r'\b(minut(ter|tere)?)(?=[\s,\.])': 'minutter',
        r'\b(modtag(ere|er|et|e))(?=[\s,\.])': 'modtage',
        r'\b(modtagelse(r|n)?)(?=[\s,\.])': 'modtage',
        r'\b(mulighed(ere|er))': 'mulighed',
        r'(møde(r|t|s)?)(?=[\s,\.])': 'møde', # Corrects all forms of words ending in variants of 'møde'
        r'\b(måned(er|en|s)?)(?=[\s,\.])': 'måned',
        r'\b(noter(e|er|et|e))(?=[\s,\.])': 'notere',
        r'\b(nr|nummer)': 'nummer',
        r'\b(obligatorisk(e)?)(?=[\s,\.])': 'obligatoriske',
        r'\b(omfatte(r|t))': 'omfatte',
        r'\b(opgave(rne|r))': 'opgave',
        r'\b(opdater(ing(erne|ne|er)?|er|et|e)?)(?=[\s,\.])': 'opdatere',
        r'\b(opfyld(ning(erne|ne|er)?|er|et|e|t)?)(?=[\s,\.])': 'opfylde',
        r'\b(opkræv(ning(erne|ne|er)?|er|et|e|t)?)(?=[\s,\.])': 'opkræve',
        r'\b(oplev(else(rne|er|ne)?|er|es|et|e|t)?)(?=[\s,\.])': 'opleve',
        r'\b(oplys(er|es|e|t)?)(?=[\s,\.])': 'oplysning',
        r'\b(oplysning(erne|er|ne)?)(?=[\s,\.])': 'oplysning',
        r'\b(oplyseninger|oplyseningerne)': 'oplysning',
        r'\b(oprette(r|t))': 'oprette',
        r'\b(opsig(elsen|else|er|e)?)(?=[\s,\.])': 'opsige',
        r'\b(optjen(er|te|e|t)?)(?=[\s,\.])': 'optjene',
        r'\b(overflyt(ning|ter|tet|te)?)(?=[\s,\.])': 'overflytte',
        r'\b(peng(ene|e))': 'penge',
        r'\b(pension(er))': 'pension',
        r'\b(period(er|en|e))': 'periode',
        r'\b(problem(erne|er|et))': 'problem',
        r'\b(profil(en|er))': 'profil',
        r'\b(præmie(r)?)(?=[\s,\.])': 'præmie',
        r'\b(prøve(t|r)?)(?=[\s,\.])': 'prøve',
        r'\b(registr(eret|ing|ere|et|er|e)?)(?=[\s,\.])': 'registrere',
        r'\b(regl(erne|er))': 'regler',
        r'\b(regning(erne|er|en))': 'regning',
        r'\b(regn(et|er|e)?)(?=[\s,\.])': 'regne',
        r'\b(rejse(r))': 'rejse',
        r'\b(rette(t|s))': 'rette',
        r'\b(rigtig(t|e)?)(?=[\s,\.])': 'rigtige',
        r'\b(ring(ede|et|er|e))': 'ringe',
        r'\b(rykke(t)?)(?=[\s,\.])': 'rykke',
        r'\b(sag(en|er)?)(?=[\s,\.])': 'sag',
        r'\b(sat(sen|ser|s)?)(?=[\s,\.])': 'sats',
        r'(samtale(rne|n|r)?)(?=[\s,\.])': 'samtale', # Corrects all forms of words ending in variants of 'samtale'
        r'(send(ete|et|te|es|er|e|t)?)(?=[\s,\.])': 'sende',  # Corrects all forms of words ending in variants of 'sende'
        r'\b(senest(e)?)(?=[\s,\.])': 'seneste',
        r'(side(n|r)?)(?=[\s,\.])': 'side', # Corrects all forms of words ending in variants of 'side'
         r'\b(sige(r)?)(?=[\s,\.])': 'sige',
        r'\b(skattefri(t|e)?)(?=[\s,\.])': 'skattefri',
        r'\b(skema(erne|et|er)?)(?=[\s,\.])': 'skema',
        r'\b(skylde(s)?)(?=[\s,\.])': 'skylde',
        r'\b(slette(t|s)?)(?=[\s,\.])': 'slette',
        r'\b(snak(ker|ket|ke))(?=[\s,\.])': 'snakke',
        r'\b(specifikation(en|er))(?=[\s,\.])': 'specifikation',
        r'\b(spørgsmål(ene|et)?)(?=[\s,\.])': 'spørgsmål',
        r'\b(start(ede|es|et|er|en|e)?)(?=[\s,\.])': 'starte',
        r'\b(sted(et|er)?)(?=[\s,\.])': 'sted',
        r'\b(stillingsopslag)': 'opslag',
        r'\b(stilling(erne|en|er)?)(?=[\s,\.])': 'stilling',
        r'\b(støt(tet|ter|ten|te)?)(?=[\s,\.])': 'støtte',
        r'\b(studiemedlemsskab(et)?)(?=[\s,\.])': 'studiemedlemskab',
        r'\b(suppler(ende|ene|et|e)?)(?=[\s,\.])': 'supplere',
        r'\b(syg(dom)?)(?=[\s,\.])': 'sygdom',
        r'\b(sygemeld(ing|t|e))':'sygemelde',
        r'\b(system(et)?)(?=[\s,\.])': 'system',
        r'\b(søg(te|er|e|t))(?=[\s,\.])': 'søge',
        r'\b(sørg(er|et|e))(?=[\s,\.])': 'sørge',
        r'\b(tal(te|er|en))': 'tale',
        r'\b(telefon(isk|en|er))': 'telefon',
        r'\b(tillad(elsen|elser|else|er|t|e))': 'tillade',
        r'\b(time(rnes|rne|rss|rs|rr|r|s)?)(?=[\s,\.])': 'time',
        r'\b(timetal(s)?)(?=[\s,\.])': 'time',
        r'\b(uge(rnes|rne|rs|n|r|s))':'uge',
        r'\b(udbetal(es|te|t)?)(?=[\s,\.])': 'udbetale',
        r'\b(udbetaling(en)?)(?=[\s,\.])': 'udbetale',
        r'\b(udfyld(er|es|te|t|e)?)(?=[\s,\.])': 'udfylde',
        r'\b(uddannelse(n))': 'uddannelse',
        r'\b(udløb(et|er|e)?)(?=[\s,\.])': 'udløbe',
        r'\b(?:underskrev(ede|ne|et))': 'underskrevne',
        r'\b(ydelseskort(et))':'ydelseskort',
        r'\b(vedhæft(ning(en|er)?|ede|et|er|e))(?=[\s,\.])': 'vedhæfte',
        r'\b(velkom(men|ne|st)?)(?=[\s,\.])': 'velkommen',
        r'\b(vent(er|ene|e)?)(?=[\s,\.])': 'vente',
        r'\b(ventelist(er|en|e)?)(?=[\s,\.])': 'venteliste',
        r'\b(virksomhed(en|er))': 'virksomhed',
        r'\b(workshop(pen|en|s))': 'workshop',
        r'\b(ændr(ede|ing(er)?|et|e))(?=[\s,\.])': 'ændre',
        r'\b(åbne(de|er|t))(?=[\s,\.])': 'åbne',
        }


re_remove = {
        r'[\w\.-]+@[\w\.-]+': '', #remove e-mail
        r'(http|ftp|https):\/\/([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:\/~+#-]*[\w@?^=%&\/~+#-])?' : '', # remove url from text
        }